export const WILAYAS: Record<number, string> = {
    1: 'Adrar',
    2: 'Chlef',
    3: 'Laghouat',
    4: 'Oum El Bouaghi',
    5: 'Batna',
    6: 'Béjaïa',
    7: 'Biskra',
    8: 'Béchar',
    9: 'Blida',
    10: 'Bouira',
    11: 'Tamanrasset',
    12: 'Tébessa',
    13: 'Tlemcen',
    14: 'Tiaret',
    15: 'Tizi Ouzou',
    16: 'Algiers',
    17: 'Djelfa',
    18: 'Jijel',
    19: 'Sétif',
    20: 'Saïda',
    21: 'Skikda',
    22: 'Sidi Bel Abbès',
    23: 'Annaba',
    24: 'Guelma',
    25: 'Constantine',
    26: 'Médéa',
    27: 'Mostaganem',
    28: 'MSila',
    29: 'Mascara',
    30: 'Ouargla',
    31: 'Oran',
    32: 'El Bayadh',
    33: 'Illizi',
    34: 'Bordj Bou Arréridj',
    35: 'Boumerdès',
    36: 'El Tarf',
    37: 'Tindouf',
    38: 'Tissemsilt',
    39: 'El Oued',
    40: 'Khenchela',
    41: 'Souk Ahras',
    42: 'Tipaza',
    43: 'Mila',
    44: 'Aïn Defla',
    45: 'Naâma',
    46: 'Aïn Témouchent',
    47: 'Ghardaïa',
    48: 'Relizane',
    49: 'Timimoun',
    50: 'Bordj Badji Mokhtar',
    51: 'Ouled Djellal',
    52: 'Béni Abbès',
    53: 'In Salah',
    54: 'In Guezzam',
    55: 'Touggourt',
    56: 'Djanet',
    57: 'El M’Ghair',
    58: 'El Meniaa',
};

export enum WilayaEnum {
    Adrar = 1,
    Chlef,
    Laghouat,
    OumElBouaghi,
    Batna,
    Béjaïa,
    Biskra,
    Béchar,
    Blida,
    Bouira,
    Tamanrasset,
    Tébessa,
    Tlemcen,
    Tiaret,
    TiziOuzou,
    Algiers,
    Djelfa,
    Jijel,
    Sétif,
    Saïda,
    Skikda,
    SidiBelAbbès,
    Annaba,
    Guelma,
    Constantine,
    Médéa,
    Mostaganem,
    MSila,
    Mascara,
    Ouargla,
    Oran,
    ElBayadh,
    Illizi,
    BordjBouArréridj,
    Boumerdès,
    ElTarf,
    Tindouf,
    Tissemsilt,
    ElOued,
    Khenchela,
    SoukAhras,
    Tipaza,
    Mila,
    AïnDefla,
    Naâma,
    AïnTémouchent,
    Ghardaïa,
    Relizane,
    Timimoun,
    BordjBadjiMokhtar,
    OuledDjellal,
    BéniAbbès,
    InSalah,
    InGuezzam,
    Touggourt,
    Djanet,
    ElMGhair,
    ElMeniaa,
}

import { z } from 'zod';

// Create the schema
const wilayaCodeSchema = z.union([
    z.literal(1), z.literal(2), z.literal(3), z.literal(4), z.literal(5),
    z.literal(6), z.literal(7), z.literal(8), z.literal(9), z.literal(10),
    z.literal(11), z.literal(12), z.literal(13), z.literal(14), z.literal(15),
    z.literal(16), z.literal(17), z.literal(18), z.literal(19), z.literal(20),
    z.literal(21), z.literal(22), z.literal(23), z.literal(24), z.literal(25),
    z.literal(26), z.literal(27), z.literal(28), z.literal(29), z.literal(30),
    z.literal(31), z.literal(32), z.literal(33), z.literal(34), z.literal(35),
    z.literal(36), z.literal(37), z.literal(38), z.literal(39), z.literal(40),
    z.literal(41), z.literal(42), z.literal(43), z.literal(44), z.literal(45),
    z.literal(46), z.literal(47), z.literal(48), z.literal(49), z.literal(50),
    z.literal(51), z.literal(52), z.literal(53), z.literal(54), z.literal(55),
    z.literal(56), z.literal(57), z.literal(58),
]);

// Optional: Type from schema
export type WilayaCode = z.infer<typeof wilayaCodeSchema>;